
name: update-website

jobs:
  update-website:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: '3.6'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}

    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          brew install pandoc-citeproc
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", 'bookdown','DBI','RMySQL','data.table','knitr','rmarkdown','DT','webshot','PhantomJS', 'bibtex','googlesheets4','tictoc','devtools','janitor','anytime','recipes','parsnip','rsample','modelr','tidymodels','tidyverse','emo'))
          devtools::install_github('hadley/emo')
          devtools::install_github('ries9112/PredictCrypto')
        shell: Rscript {0}
      - name: Refresh book
        run: |
          bookdown::render_book('index.Rmd', 'bookdown::gitbook', clean_envir = FALSE)
        shell: Rscript {0}
